name: book_my_doctor
description: Book My Doctor.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_fonts: ^1.1.2
  flutter_svg: ^0.19.1
  intro_slider: ^2.3.4
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  flutter_rating_bar: ^4.0.0
  random_string: ^2.1.0
  chat_bubbles: ^0.8.0
  timeago: ^3.0.2
#  google_maps_flutter: ^2.0.10
#  google_map_location_picker: ^4.1.7
  google_map_location_picker:
    git:
      url: git://github.com/lyokone/google_map_location_picker.git
  flutter_localizations:
    sdk: flutter

  geocoder: ^0.2.1
#  geocoder:
#    git:
#      url: https://github.com/nguyenxdat/flutter_geocoder.git

  carousel_slider: ^3.0.0

#  provider: ^5.0.0

  firebase_core: ^1.6.0
  #  Auth
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  flutter_facebook_login: ^3.0.0
  #  Database
  cloud_firestore: ^2.5.3
  #  Storage
  firebase_storage: ^10.0.3
  shared_preferences: ^2.0.4

  #  Image, FILE, Permission
  cached_network_image: ^2.5.1
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.0
  file_picker: ^4.1.0
  path_provider: ^2.0.1
  permission_handler: ^6.0.1+1

  #  Map
  maps_launcher: ^2.0.1
  url_launcher: ^6.0.11

  #  Payment Integration
#  paytm_allinonesdk: ^1.0.0
  razorpay_flutter: ^1.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^0.13.0
  plugin_platform_interface: ^2.0.1
  provider: ^6.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
